plugins {
    id "com.android.test"
    id "androidx.baselineprofile"
}

android {
    namespace "com.k2.music.benchmark"
    compileSdk 37

    defaultConfig {
        minSdk 28
        targetSdk 36
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        testInstrumentationRunnerArguments clearPackageData: "true"
    }

    targetProjectPath = ":app"
    experimentalProperties["android.experimental.self-instrumenting"] = true

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

baselineProfile {
    useConnectedDevices = true
}

dependencies {
    implementation "androidx.test.ext:junit:1.3.0"
    implementation "androidx.test:runner:1.7.0"
    implementation "androidx.test.uiautomator:uiautomator:2.3.0"
    implementation "androidx.benchmark:benchmark-macro-junit4:1.5.0-alpha07"
}
